server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  #      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    local:
      amap-key: 824c511f0997586ea016f979fdb23087  # 高德地图 key
  domain:
    default: kiki.lijie:8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: kiki
    # 发送消息的超时时间，单位是毫秒
    send-message-timeout: 2000
    # 同步模式下，消息发送失败后的重试次数
    retry-times-when-send-failed: 3
    # 异步模式下，消息发送失败后的重试次数
    retry-times-when-send-async-failed: 3
